
- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present

- name: Limit SSH attempts
  community.general.ufw:
    rule: limit
    port: 22
    proto: tcp

- name: Allow SSH
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Set default incoming policy to deny
  ufw:
    default: deny
    direction: incoming

- name: Set default outgoing policy to allow
  ufw:
    default: allow
    direction: outgoing

- name: Enable UFW
  ufw:
    state: enabled
